### ISSUE TITLE
Initialization Error on MacOS Catalina

### ISSUE THREAD

**Issue by jordychetty** [EntelectChallenge/2020-Overdrive#6]
I'm getting the following error when running the starter-pack on **MacOS Catalina v10.15**:

```
Exception in thread "main" java.lang.NoSuchFieldException: scl
        at java.base/java.lang.Class.getDeclaredField(Class.java:2416)
        at za.co.entelect.challenge.engine.bootstrapper.GameBootstrapper.setupSystemClassloader(GameBootstrapper.java:206)
        at za.co.entelect.challenge.engine.bootstrapper.GameBootstrapper.main(GameBootstrapper.java:54)
```

I've tried running the program from terminal using the batch script command provided in _run.bat_, using the  makefile with no avail.

If using an operating system other than Windows or Linux, are we expected to compile the jar and dependencies?

**Comment by craig95** [comment]
@jordychetty I ran `make run` on macOS Catalina v10.15 in the starter pack directory and it worked fine. I just followed the Linux instructions since macOS also uses the Unix shell.

But I think you the problem lies elsewhere, I think it might be a problem with your Java installation or the version of Java you have installed? 

The instructions also ask that we ask for help on their forum: "ou should now see some text whizz by in the console/terminal. If this is not the case, your match didn't run as it should. If the error message isn't clear, you can ask for help on [our forum](https://forum.entelect.co.za/)."

**Comment by jordychetty** [comment]
@craig95 what are the specifics of your Java installation?

Aside, when the issue gets resolved I'll post the details on the forum for completeness sake.

**Comment by Mistborn94** [comment]
Hi All
This issue has been resolved on the develop branch :) We will be releasing a new starter pack soon that contains the fix.
